### ISSUE TITLE
static content sample

### ISSUE THREAD

**Issue by eprogramming** [wildfly-swarm/example-servlet-cdi#1]
hi @kenfinnigan , how we can use index.html / *.css / *.js ?
thanks for this example + 1

**Comment by kenfinnigan** [comment]
Do you have an example project/repo of what you're looking to achieve?

Might be easier to convert that to work with WildFly Swarm

**Comment by eprogramming** [comment]
@kenfinnigan 

yup https://github.com/aeshell/nanook/tree/with-wildfly-swarm

I just need *.css *.js *.html

**Comment by bobmcwhirter** [comment]
Yah, I'd definitely like to make static resources easy to serve.  Dunno if that's some flavor of StaticResourceDeployment or something else.  Configuring a resource-servlet is a pain when you just want to serve up files from within the jar or filesystem.

**Comment by eprogramming** [comment]
@bobmcwhirter 
this feature would be very good

+1

**Comment by kenfinnigan** [comment]
This issue was moved to wildfly-swarm/wildfly-swarm#21
